# Generated by Django 4.2.14 on 2024-08-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_users_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='account number'),
        ),
    ]
