# Generated by Django 4.2.14 on 2024-08-06 12:40

import account.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_users_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[account.helpers.clean_mobile_number], verbose_name='mobile number'),
        ),
    ]
