# Generated by Django 4.2.14 on 2024-10-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriends',
            name='status',
            field=models.CharField(default='pending', max_length=50, verbose_name='Status of request'),
        ),
    ]
