# Generated by Django 4.2.14 on 2024-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userfriends_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_file',
            field=models.BooleanField(blank=True, default=False, verbose_name='wheather message is a file'),
        ),
    ]
